"""Turns screen + signal results into a human-readable Markdown report."""

from __future__ import annotations

from datetime import date, datetime
from typing import Dict, List, Optional, Tuple

from .data_provider import NewsItem
from .filings import FilingItem
from .macro import MacroSnapshot
from .sentiment import SentimentTag
from .shariah_screen import ScreenResult
from .signals import TradeSignal

DISCLAIMER = """\
> **Not financial or Shariah advice.** This report is generated by a rules-based
> screen (see `README.md` for methodology). It is *not* a certified Shariah
> ruling -- cross-check any name you actually intend to trade against a
> certified source (Zoya / Musaffa / Islamicly / your own scholar). It is
> also not investment advice, and past price action does not predict future
> returns. Trade Republic has no public trading API, so nothing here places
> an order for you -- you decide, and you execute, manually. Short-term
> trading can lose money quickly; never risk more than you can afford to lose.
"""


def build_report(
    ranked: List[Tuple[ScreenResult, TradeSignal]],
    screened_out: List[ScreenResult],
    not_qualifying: List[Tuple[ScreenResult, TradeSignal]],
    skipped: List[str],
    as_of: date | None = None,
    news: Optional[Dict[str, List[NewsItem]]] = None,
    sentiment: Optional[Dict[str, SentimentTag]] = None,
    filings: Optional[Dict[str, List[FilingItem]]] = None,
    macro: Optional[MacroSnapshot] = None,
    track_record_summary: Optional[dict] = None,
) -> str:
    as_of = as_of or datetime.utcnow().date()
    total = len(ranked) + len(screened_out) + len(not_qualifying) + len(skipped)
    lines = [
        f"# Halal short-term watchlist -- {as_of.isoformat()}",
        "",
        DISCLAIMER,
        f"Universe screened: {total} symbols. "
        f"Shariah-compliant candidates with a qualifying setup: **{len(ranked)}**.",
        "",
    ]

    if macro is not None:
        lines.append("## Macro snapshot")
        lines.append("")
        if macro.vix is not None:
            lines.append(f"- VIX: {macro.vix} ({macro.vix_label})")
        if macro.ten_year_yield_pct is not None:
            lines.append(f"- 10-year Treasury yield: {macro.ten_year_yield_pct}%")
        lines.append(
            "- Informational only -- not a filter, doesn't change ranking or sizing. "
            "Weigh it yourself."
        )
        lines.append("")

    if track_record_summary is not None:
        lines.append("## Track record so far")
        lines.append("")
        lines.append(
            f"- {track_record_summary['count']} resolved trades, "
            f"{track_record_summary['wins']} wins "
            f"({track_record_summary['win_rate']}% win rate), "
            f"average return {track_record_summary['avg_return_pct']:+.2f}%."
        )
        lines.append(
            "- Descriptive only, not a forward-looking probability -- too small a "
            "sample to mean much yet. Grows with every resolved trade."
        )
        lines.append("")

    if ranked:
        lines.append(
            "| # | Symbol | Close | RSI | Rel.Vol | Stop | Target | R:R | Max hold | Score |"
        )
        lines.append("|---|---|---|---|---|---|---|---|---|---|")
        for i, (screen, sig) in enumerate(ranked, start=1):
            lines.append(
                f"| {i} | **{sig.symbol}** | {sig.last_close} | {sig.rsi} | "
                f"{sig.relative_volume}x | {sig.stop_loss} | {sig.target} | "
                f"{sig.reward_risk} | {sig.max_holding_days}d | {sig.score} |"
            )
        lines.append("")
        lines.append(
            "Stop/target are mechanical (ATR-based) reference points, not guarantees -- "
            "size each position so a stop-out is a small, plannable loss, and exit by the "
            "time-stop regardless of price if neither level is hit."
        )
        lines += [
            "",
            "### Recent headlines (unverified -- for manual catalyst review only)",
            "",
            "Not scored, not investment advice, and not fact-checked -- purely so you can "
            "eyeball whether there's an obvious reason behind the move before acting on it. "
            "Cross-check anything that matters against a primary source.",
            "",
        ]
        news = news or {}
        sentiment = sentiment or {}
        for _screen, sig in ranked:
            items = news.get(sig.symbol, [])
            if not items:
                lines.append(f"- **{sig.symbol}**: no recent headlines found -- check manually.")
                continue
            tag = sentiment.get(sig.symbol)
            if tag is not None:
                lines.append(
                    f"- **{sig.symbol}** -- sentiment {tag.sentiment:+.2f} "
                    f"({tag.event_type}, {tag.confidence} confidence) "
                    f"*[LLM-generated summary of the headlines below, not a "
                    f"prediction -- not scored, not combined with the quant "
                    f"signal above]*: {tag.rationale}"
                )
            else:
                lines.append(f"- **{sig.symbol}**:")
            for item in items:
                meta_parts = [p for p in (item.publisher, item.published) if p]
                meta = f" ({', '.join(meta_parts)})" if meta_parts else ""
                headline = f"[{item.title}]({item.link})" if item.link else item.title
                lines.append(f"  - {headline}{meta}")

        lines += [
            "",
            "### Recent SEC filings (unverified -- for manual review only)",
            "",
            "8-K filings only (material events). Only covers SEC filers -- a US-listed "
            "or SEC-registered symbol; a non-US ticker will always show none here, which "
            "is expected, not a failure.",
            "",
        ]
        filings = filings or {}
        for _screen, sig in ranked:
            items = filings.get(sig.symbol, [])
            if not items:
                lines.append(f"- **{sig.symbol}**: no recent 8-K filings found.")
                continue
            lines.append(f"- **{sig.symbol}**:")
            for item in items:
                entry = f"{item.form} ({item.filed})"
                lines.append(f"  - [{entry}]({item.url})" if item.url else f"  - {entry}")
    else:
        lines.append("_No symbol passed both the Shariah screen and the trade-setup filters today._")

    if screened_out:
        lines += ["", "## Excluded on Shariah screen", ""]
        for s in screened_out:
            lines.append(f"- **{s.symbol}**: {'; '.join(s.reasons)}")

    if not_qualifying:
        lines += [
            "",
            "## Shariah-compliant, but no qualifying setup today",
            "",
            "Passed the screen -- just nothing worth entering right now (wrong "
            "trend/momentum/volume). Worth re-checking on a future run, not excluded "
            "for cause.",
            "",
        ]
        for screen, sig in not_qualifying:
            lines.append(f"- **{sig.symbol}**: {'; '.join(sig.reasons_excluded)}")

    if skipped:
        lines += ["", "## Skipped (data unavailable)", ""]
        for sym in skipped:
            lines.append(f"- {sym}")

    lines += ["", "---", "_Generated by the halal_trader research agent._"]
    return "\n".join(lines) + "\n"
