"""Turns screen + signal results into a human-readable Markdown report."""

from __future__ import annotations

from datetime import date, datetime
from typing import Dict, List, Optional, Tuple

from .data_provider import NewsItem
from .events import HoldContext
from .filings import FilingItem
from .macro import MacroSnapshot
from .sentiment import SentimentTag
from .shariah_screen import ScreenResult
from .risk import cost_drag_pct, order_ticket
from .signals import TradeSignal
from .trades import Trade, trade_return_pct

DISCLAIMER = """\
> **Not financial or Shariah advice.** This report is generated by a rules-based
> screen (see `README.md` for methodology). It is *not* a certified Shariah
> ruling -- cross-check any name you actually intend to trade against a
> certified source (Zoya / Musaffa / Islamicly / your own scholar). It is
> also not investment advice, and past price action does not predict future
> returns. Trade Republic has no public trading API, so nothing here places
> an order for you -- you decide, and you execute, manually. Short-term
> trading can lose money quickly; never risk more than you can afford to lose.
"""


def build_report(
    ranked: List[Tuple[ScreenResult, TradeSignal]],
    screened_out: List[ScreenResult],
    not_qualifying: List[Tuple[ScreenResult, TradeSignal]],
    skipped: List[str],
    as_of: date | None = None,
    news: Optional[Dict[str, List[NewsItem]]] = None,
    sentiment: Optional[Dict[str, SentimentTag]] = None,
    filings: Optional[Dict[str, List[FilingItem]]] = None,
    macro: Optional[MacroSnapshot] = None,
    track_record_summary: Optional[dict] = None,
    hold: Optional[HoldContext] = None,
    positions: Optional[List[dict]] = None,
    real_summary: Optional[dict] = None,
    correlations: Optional[Dict[str, List[tuple]]] = None,
    digests: Optional[Dict[str, str]] = None,
    comparison: Optional[List[dict]] = None,
) -> str:
    as_of = as_of or datetime.utcnow().date()
    total = len(ranked) + len(screened_out) + len(not_qualifying) + len(skipped)
    lines = [
        f"# Halal short-term watchlist -- {as_of.isoformat()}",
        "",
        DISCLAIMER,
        f"Universe screened: {total} symbols. "
        f"Shariah-compliant candidates with a qualifying setup: **{len(ranked)}**.",
        "",
    ]

    if macro is not None:
        lines.append("## Macro snapshot")
        lines.append("")
        if macro.vix is not None:
            lines.append(f"- VIX: {macro.vix} ({macro.vix_label})")
        if macro.ten_year_yield_pct is not None:
            lines.append(f"- 10-year Treasury yield: {macro.ten_year_yield_pct}%")
        lines.append(
            "- Informational only -- not a filter, doesn't change ranking or sizing. "
            "Weigh it yourself."
        )
        lines.append("")

    if positions:
        lines.append("## Your open positions")
        lines.append("")
        lines.append("| Symbol | Entry | Stop | Target | Time-stop | Trading days left |")
        lines.append("|---|---|---|---|---|---|")
        for p in positions:
            t: Trade = p["trade"]
            entry = (
                f"{t.entry_date.isoformat()} @ {t.entry_price} {t.currency}".strip()
                if t.entry_date and t.entry_price
                else "entry unconfirmed"
            )
            stop = t.stop if t.stop is not None else "--"
            target = t.target if t.target is not None else "--"
            if p["time_stop"] is None:
                ts, left = "unknown (no entry date)", "--"
            elif p["overdue"]:
                ts, left = f"**{p['time_stop'].isoformat()}**", "**OVERDUE -- exit now**"
            elif p["days_left"] == 0:
                ts, left = f"**{p['time_stop'].isoformat()}**", "**0 -- exit today**"
            else:
                ts, left = p["time_stop"].isoformat(), str(p["days_left"])
            lines.append(f"| **{t.symbol}** | {entry} | {stop} | {target} | {ts} | {left} |")
        lines.append("")
        lines.append(
            "From `track_record/real_trades.csv` (your actual fills; the day count starts "
            "on the actual entry day). Exit by the time-stop regardless of price."
        )
        lines.append("")

    if positions:
        lines += _do_today_lines(positions, as_of, hold)

    if real_summary is not None:
        lines.append("## Your real trades so far")
        lines.append("")
        lines.append(
            f"- {real_summary['count']} closed, {real_summary['wins']} wins "
            f"({real_summary['win_rate']}% win rate), average return "
            f"{real_summary['avg_return_pct']:+.2f}% (app-reported or fill-based, "
            f"before tax, fees partly excluded)."
        )
        lines.append("- Tiny sample -- descriptive only, no evidence of edge.")
        lines.append("")
        matched = [c for c in (comparison or []) if c["matched"]]
        if matched:
            lines.append("### Your exits vs the plan's (same trades, simulated to the letter)")
            lines.append("")
            lines.append("| Symbol | Your return | Plan-following return | Plan exit |")
            lines.append("|---|---|---|---|")
            for c in matched:
                real = f"{c['real_pct']:+.2f}%" if c["real_pct"] is not None else "--"
                lines.append(f"| {c['symbol']} | {real} | {c['plan_pct']:+.2f}% | {c['plan_exit']} |")
            reals = [c["real_pct"] for c in matched if c["real_pct"] is not None]
            plans = [c["plan_pct"] for c in matched]
            if reals and plans:
                lines.append(
                    f"| **avg** | **{sum(reals)/len(reals):+.2f}%** | "
                    f"**{sum(plans)/len(plans):+.2f}%** | |"
                )
            lines.append("")
            lines.append(
                "- Discipline check, not a verdict: the plan column assumes entry at the "
                "ranking day's close and mechanical exits with slippage. Needs 30+ trades "
                "to mean anything."
            )
            lines.append("")

    if track_record_summary is not None:
        lines.append("## Track record so far")
        lines.append("")
        lines.append(
            "- *Simulated: every flagged candidate, as if taken at the report's close "
            "(not your actual trades -- see the real-trades section).*"
        )
        lines.append(
            f"- {track_record_summary['count']} resolved trades, "
            f"{track_record_summary['wins']} wins "
            f"({track_record_summary['win_rate']}% win rate), "
            f"average return {track_record_summary['avg_return_pct']:+.2f}%."
        )
        lines.append(
            "- Descriptive only, not a forward-looking probability -- too small a "
            "sample to mean much yet. Grows with every resolved trade."
        )
        lines.append("")

    if ranked:
        lines.append(
            "| # | Symbol | Close | RSI | Rel.Vol | Stop | Target | R:R | Max hold | Score |"
        )
        lines.append("|---|---|---|---|---|---|---|---|---|---|")
        for i, (screen, sig) in enumerate(ranked, start=1):
            lines.append(
                f"| {i} | **{sig.symbol}** | {sig.last_close} | {sig.rsi} | "
                f"{sig.relative_volume}x | {sig.stop_loss} | {sig.target} | "
                f"{sig.reward_risk} | {sig.max_holding_days}d | {sig.score} |"
            )
        lines.append("")
        lines.append(
            "Stop/target are mechanical (ATR-based) reference points, not guarantees -- "
            "size each position so a stop-out is a small, plannable loss, and exit by the "
            "time-stop regardless of price if neither level is hit."
        )
        lines += _order_ticket_lines(ranked)
        lines += _entry_context_lines(ranked, hold, positions, as_of, correlations)
        lines += [
            "",
            "### Recent headlines (unverified -- for manual catalyst review only)",
            "",
            "Not scored, not investment advice, and not fact-checked -- purely so you can "
            "eyeball whether there's an obvious reason behind the move before acting on it. "
            "Cross-check anything that matters against a primary source.",
            "",
        ]
        news = news or {}
        sentiment = sentiment or {}
        for sym in _coverage_symbols(ranked, positions):
            items = news.get(sym, [])
            if not items:
                lines.append(f"- **{sym}**: no recent headlines found -- check manually.")
                continue
            tag = sentiment.get(sym)
            if tag is not None:
                lines.append(
                    f"- **{sym}** -- sentiment {tag.sentiment:+.2f} "
                    f"({tag.event_type}, {tag.confidence} confidence) "
                    f"*[LLM-generated summary of the headlines below, not a "
                    f"prediction -- not scored, not combined with the quant "
                    f"signal above]*: {tag.rationale}"
                )
            else:
                lines.append(f"- **{sym}**:")
            for item in items:
                meta_parts = [p for p in (item.publisher, item.published) if p]
                meta = f" ({', '.join(meta_parts)})" if meta_parts else ""
                headline = f"[{item.title}]({item.link})" if item.link else item.title
                lines.append(f"  - {headline}{meta}")

        lines += [
            "",
            "### Recent SEC filings (unverified -- for manual review only)",
            "",
            "8-K filings only (material events). Only covers SEC filers -- a US-listed "
            "or SEC-registered symbol; a non-US ticker will always show none here, which "
            "is expected, not a failure.",
            "",
        ]
        filings = filings or {}
        for sym in _coverage_symbols(ranked, positions):
            items = filings.get(sym, [])
            if not items:
                lines.append(f"- **{sym}**: no recent 8-K filings found.")
                continue
            lines.append(f"- **{sym}**:")
            for item in items:
                entry = f"{item.form} ({item.filed})"
                lines.append(f"  - [{entry}]({item.url})" if item.url else f"  - {entry}")
        digests = digests or {}
        if digests:
            lines += [
                "",
                "### Filing digests (your positions -- LLM summary, verify before relying on it)",
                "",
            ]
            for sym, d in digests.items():
                lines.append(f"- **{sym}**: {d}")
    else:
        lines.append("_No symbol passed both the Shariah screen and the trade-setup filters today._")

    if screened_out:
        lines += ["", "## Excluded on Shariah screen", ""]
        for s in screened_out:
            lines.append(f"- **{s.symbol}**: {'; '.join(s.reasons)}")

    if not_qualifying:
        lines += [
            "",
            "## Shariah-compliant, but no qualifying setup today",
            "",
            "Passed the screen -- just nothing worth entering right now (wrong "
            "trend/momentum/volume). Worth re-checking on a future run, not excluded "
            "for cause.",
            "",
        ]
        for screen, sig in not_qualifying:
            lines.append(f"- **{sig.symbol}**: {'; '.join(sig.reasons_excluded)}")

    if skipped:
        lines += ["", "## Skipped (data unavailable)", ""]
        for sym in skipped:
            lines.append(f"- {sym}")

    lines += ["", "---", "_Generated by the halal_trader research agent._"]
    return "\n".join(lines) + "\n"


def _entry_context_lines(ranked, hold, positions, as_of, correlations=None) -> List[str]:
    """Entry-timing flags (52-week-high distance / overhead resistance) and
    what is scheduled inside the hold window. Warnings only: nothing here
    changes ranking, and none of it replaces ADVISORY_PROTOCOL section 3."""
    held = {p["trade"].symbol for p in (positions or [])}
    lines = ["", "### Entry-timing flags (52-week high / overhead resistance)", ""]
    for _screen, sig in ranked:
        bits = []
        if sig.pct_below_52w_high is not None:
            bits.append(f"{sig.pct_below_52w_high:.1f}% below its high of {sig.high_52w}")
        if sig.rr_to_52w_high is not None:
            bits.append(f"reward:risk up to that high = {sig.rr_to_52w_high:.2f}:1")
        if sig.symbol in held:
            bits.append("**already in your open positions**")
        for pos_sym, corr in (correlations or {}).get(sig.symbol, []):
            bits.append(
                f"⚠ {corr:+.2f} return correlation with your open {pos_sym} position "
                f"-- partly the same bet, not diversification"
            )
        lines.append(f"- **{sig.symbol}**: " + "; ".join(bits) if bits else f"- **{sig.symbol}**: no data")
        for w in sig.warnings:
            lines.append(f"  - ⚠ {w}")
    lines.append(
        "- The reward:risk in the main table is fixed by construction (always 1.5:1); "
        "this section is the only place it is compared with where price has actually been."
    )
    from . import config as _cfg

    lines.append(
        f"- Cost note: at a {_cfg.TYPICAL_POSITION_EUR:.0f} EUR position, round-trip fees "
        f"({2 * _cfg.FEE_PER_ORDER_EUR:.0f} EUR) are {cost_drag_pct():.2f}% -- the backtested "
        f"average per trade was +0.27%, so fees alone consume most of it at this size. "
        f"Smaller positions make that worse."
    )

    if hold is not None and hold.window:
        first, last = hold.window[0], hold.window[-1]
        lines += [
            "",
            f"### Events inside a {len(hold.window)}-day hold "
            f"({first.isoformat()} -> {last.isoformat()}, if entered {first.isoformat()})",
            "",
        ]
        if hold.macro_events:
            for e in hold.macro_events:
                lines.append(f"- ⚠ {e.day.isoformat()} ({e.day.strftime('%a')}): {e.name}")
        elif hold.calendar_ok:
            lines.append("- No scheduled macro events in `data/event_calendar.csv` for this window.")
        else:
            lines.append(
                "- ⚠ `data/event_calendar.csv` does not reach the end of this window -- "
                "macro events could not be checked. Update the file."
            )
        for _screen, sig in ranked:
            d = hold.earnings.get(sig.symbol)
            if d is None:
                lines.append(f"- **{sig.symbol}** earnings date unavailable -- check manually.")
            elif first <= d <= last:
                lines.append(f"- ⚠ **{sig.symbol}** reports earnings on {d.isoformat()} -- INSIDE the hold window.")
            else:
                lines.append(f"- **{sig.symbol}** next earnings {d.isoformat()} (outside the window).")
    return lines


def _order_ticket_lines(ranked) -> List[str]:
    """Mechanical order tickets: every number filled in by formula, no
    judgment anywhere. The decision to act stays with the reader."""
    from . import config as _cfg

    lines = [
        "",
        "### Order tickets (mechanical sizing -- NOT a recommendation to enter)",
        "",
        f"size = (portfolio {_cfg.PORTFOLIO_EUR:.0f} EUR x {_cfg.RISK_PCT_PER_TRADE:g}% risk) / "
        f"(entry - stop), capped at {_cfg.MAX_POSITION_PCT_OF_PORTFOLIO:.0f}% of the portfolio. "
        "Prices below are in the data currency (USD for US names) -- convert at your actual "
        "EUR fill: same percentages, same share count. Enter at most ONE of these unless "
        "aggregate risk stays within your cap.",
        "",
    ]
    if _cfg.RISK_PCT_PER_TRADE > 2.0:
        lines += [
            f"⚠ **Risk setting: {_cfg.RISK_PCT_PER_TRADE:g}% of the account per trade** "
            f"(common practice: 0.5-2%). Three consecutive stop-outs cost "
            f"~{3 * _cfg.RISK_PCT_PER_TRADE:.0f}% of the account at this setting.",
            "",
        ]
    lines.append(
        "| Symbol | Shares | Position value | Entry (last close) | Stop (sell if below) "
        "| Target (sell limit) | At stop | At target | Exit by |"
    )
    lines.append("|---|---|---|---|---|---|---|---|---|")
    from .events import time_stop_date
    from datetime import date as _date

    for _screen, sig in ranked:
        if sig.stop_loss is None or sig.target is None or sig.last_close is None:
            continue
        t = order_ticket(sig.last_close, sig.stop_loss, sig.target)
        if t is None:
            continue
        cap = " (capped: no leverage)" if t["capped"] else ""
        lines.append(
            f"| **{sig.symbol}** | {t['shares']} | {t['position_value']:.2f}{cap} | "
            f"{sig.last_close} | {sig.stop_loss} | {sig.target} | "
            f"-{t['risk_amount']:.2f} | +{t['reward_amount']:.2f} | "
            f"{sig.max_holding_days} trading days after entry |"
        )
    lines += [
        "",
        "If entered: place the stop immediately, place the target as a sell limit if your "
        "broker allows both, and sell at market on the exit-by day if neither has triggered. "
        "Update `PORTFOLIO_EUR` in `halal_trader/config.py` when the account value changes.",
    ]
    return lines


def _coverage_symbols(ranked, positions) -> List[str]:
    """Ranked names first, then held names that didn't rank -- the news,
    sentiment and filings sections cover what you own, not only what
    qualifies today."""
    syms = [sig.symbol for _s, sig in ranked]
    for p in positions or []:
        if p["trade"].symbol not in syms:
            syms.append(p["trade"].symbol)
    return syms


def _do_today_lines(positions, as_of, hold) -> List[str]:
    """The plan's required actions for TODAY, read mechanically from the
    open positions. Only time/structure rules appear here -- price-level
    exits are the standing stop/target orders' job."""
    lines = ["## Do today", ""]
    for p in positions:
        t = p["trade"]
        if p["time_stop"] is None:
            lines.append(
                f"- **{t.symbol}: entry date missing** -- add it to "
                f"`track_record/real_trades.csv`, the 5-day clock can't run without it."
            )
        elif p["overdue"]:
            lines.append(
                f"- **SELL {t.symbol} TODAY -- time-stop was {p['time_stop'].isoformat()} "
                f"and is OVERDUE.** The plan does not hold past it at any price."
            )
        elif p["days_left"] == 0:
            lines.append(
                f"- **SELL {t.symbol} TODAY -- time-stop is today "
                f"({p['time_stop'].isoformat()}).** Exit at market before the close, "
                f"whatever the price."
            )
        elif p["days_left"] == 1:
            lines.append(
                f"- **{t.symbol}: last full day tomorrow** ({p['time_stop'].isoformat()}) "
                f"-- plan the exit now, don't leave it to the final minutes."
            )
        else:
            lines.append(
                f"- {t.symbol}: no action required ({p['days_left']} trading days to "
                f"{p['time_stop'].isoformat()})."
            )
        if t.stop is None:
            lines.append(
                f"  - ⚠ no stop recorded for {t.symbol} -- place one and record it."
            )
    todays = [e for e in (hold.macro_events if hold else []) if e.day == as_of]
    for e in todays:
        lines.append(f"- ⚠ Scheduled today: {e.name}.")
    lines += [
        "",
        "Price-level exits (stop / target) are standing orders, not daily decisions -- "
        "place them when the position is opened. This section only reads the clock.",
        "",
    ]
    return lines
